group_project-main/group_work/urls.py
from django.urls import path, include
from mylibrary import views
from django.contrib import admin

urlpatterns = [
    path('', views.index, name='index'),
    path('mylibrary/', include('mylibrary.urls')),
    path("admin/", admin.site.urls),
]

group_project-main/mylibrary/urls.py
from django.urls import path
from mylibrary import views
from django.contrib import admin

app_name = 'mylibrary'


urlpatterns = [
    path('', views.index, name='index'),
    path('add_book/', views.add_book, name='add_book'),
    path('books/<slug:book_name_slug>/', views.show_book, name='show_book'),
    path('about/', views.about, name='about'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('mygoals/', views.mygoals, name='mygoals'),
    path('set_goal/', views.mygoals, name='set_goal'),

]

group_project-main/mylibrary/models.py
from django.db import models

# Create your models here.
from django.contrib import admin
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    categoryID=models.CharField(max_length=20, unique=True)
    numOfBooks=models.IntegerField(default=0)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileLink = models.URLField(blank=True)
    profilePic=models.ImageField()


class Book(models.Model):
    ISBN=models.IntegerField(unique=True)
    author=models.CharField(max_length=50)
    uploadedBy=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    coverPhoto=models.ImageField()
    categories = models.ManyToManyField(Category)
    title=models.CharField(max_length=500)
    slug=models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super(Book,self).save(*args, **kwargs)

class Goal(models.Model):
    goalAuthor=models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    dateSet=models.DateTimeField()
    achieved=models.BooleanField()
    goalID=models.CharField(max_length=50,unique=True)
    numPages=models.IntegerField(null=True)
    dateDay=models.IntegerField(null=True)
    dateMonth=models.IntegerField(null=True)
    dateYear=models.IntegerField(null=True)
    slug=models.SlugField(unique=True)


class Admin(models.Model):
    adminID=models.CharField(max_length=50, unique=True) 

class Review(models.Model):
    reviewID=models.CharField(max_length=50, unique=True)
    dateWritten=models.DateField()
    edited=models.BooleanField(default=False)
    reviewAuthorFK=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    reviewBookFK=models.ForeignKey(Book, on_delete=models.CASCADE, null=True)

group_project-main/mylibrary/forms.py
from django import forms
from mylibrary.models import Book, Category, Review, User, Goal, Admin
from django.contrib.auth.models import User 



class BookForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Enter the title of the book")
    author = forms.CharField(max_length=50, help_text="Enter the author of the book")
    ISBN = forms.IntegerField(help_text="Enter the ISBN of the book")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    book_dict = {"title": title, "author": author,"ISBN":ISBN, "uploadedBy":None}
    
    class Meta:
        model = Book
        fields=('title', 'author','ISBN','uploadedBy')

    def set_uploaded_by(self, user):
        self.book_dict["uploadedBy"]=user

    def get_book_dict(self):
        return self.book_dict

class GoalForm(forms.ModelForm):
    ISBN = forms.IntegerField(help_text="Enter the ISBN of the book this goal refers to")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    numPages=forms.IntegerField(help_text="How many pages do you want to read?")
    dateDay=forms.IntegerField(help_text="When do you want to achieve this by? Day: ")
    dateMonth=forms.IntegerField(help_text="Month: ")
    dateYear=forms.IntegerField(help_text="Year: ")

    
    class Meta:
        model = Goal
        fields=('goalAuthor', 'dateSet','goalID','achieved', 'slug', 'dateDay', 'dateMonth', 'dateYear')

group_project-main/mylibrary/views.py
from django.shortcuts import render
from mylibrary.forms import BookForm
from django.shortcuts import redirect
import django
from django.urls import reverse
import datetime
# Create your views here.

from django.http import HttpResponse 
from mylibrary.models import Book, Category, Review, User, Goal

def index(request):
    return render(request, 'mylibrary/index.html', context={})

def myprofile(request):
    user = User.objects.get(username=request.user.username)
    context_dict={"user":user}
    return render(request, 'mylibrary/myprofile.html', context_dict)


def set_goal(request):
    form = GoalForm()

    if request.method == 'POST':
        goal =  BookForm(request.POST)
        if form.is_valid():
            goal=form.save(commit=False)
            goal.goalAuthor=request.user
            goal.dateSet=datetime.datetime.now()
            goal.save()
            return redirect(reverse('mylibrary:mygoals'))
        else:
            print(form.errors)
    
    return render(request, 'mylibrary/mygoals.html', {'form': form})

def mygoals(request):
    context_dict={}
    goals = Goal.objects.filter(goalAuthor=request.user)
    context_dict["goals"] = goals
    return render(request, "mygoals.html", context=context_dict)

def show_book(request, book_name_slug):
    context_dict={}
    try:
        book=Book.objects.get(slug=book_name_slug)
        context_dict["book"]=book
    except Book.DoesNotExist:
        context_dict['category']=None
        context_dict['pages']=None
    return render(request, "mylibrary/book.html", context=context_dict)

def add_book(request):
    form = BookForm()

    if request.method == 'POST':
        form =  BookForm(request.POST)
        if form.is_valid():
            book=form.save(commit=False)
            book.uploadedBy=request.user
            book.save()
            show_book(request, book.slug)
            return redirect(reverse('mylibrary:show_book', kwargs={'book_name_slug': book.slug}))
        else:
            print(form.errors)
    
    return render(request, 'mylibrary/add_book.html', {'form': form})

def about(request):
    return render(request, 'mylibrary/about.html', context={})

group_project-main/templates/mylibrary/about.html
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% extends 'mylibrary/base.html' %}
{% load staticfiles %}

{% block title_block %}
About MyLibrary
{% endblock %}
{% block body_block %}
<div><strong>{{ "This web page has been put together by Juliet Wallace" }}</strong><br /> </div>
<button class="btn btn-primary"
onclick="alert('You clicked the button using inline JavaScript.');">
Click me - I run on vanilla JavaScript! </button>
<button class="btn btn-primary" id="about-btn"> Click me - I'm using JQuery!
</button>
{% endblock %}

group_project-main/templates/mylibrary/add_book.html
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% extends 'mylibrary/base.html' %} 

{% block title_block %}
Add a Book
{% endblock %}

{% block body_block %}
<form id="book_form" method="post" action="/mylibrary/add_book/"> {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
{% endfor %}
<input type="submit" name="submit" value="Upload Book" />
</form>
<div>
<li><a href="{% url 'mylibrary:index' %}">Home</a></li>
</div>
{% endblock %}

group_project-main/templates/mylibrary/base-new.html
<!DOCTYPE html>
{%load staticfiles% }

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<html lang="en"> <head>
<meta
<link <title>
MyLibrary - {% block title_block %}MyLibrary{% endblock %} </title>
  <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
<link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
</head> <body> <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0"> <a class="navbar-brand p-2" href="{% url 'mylibrary:index' %}">MyLibrary</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse"> <ul class="navbar-nav mr-auto">
    <li class="nav-item">
    <a class="nav-link" href="{% url 'mylibrary:index' %}">Home</a></li> <li class="nav-item ">
    Bootstrapping Rango 208
    <li
    class="nav-item ">
    href="{% url 'mylibrary:add_book' %}">Add a Book</a></li> class="nav-item">
    <a class="nav-link"
    class="nav-item">
    </header>
    <div class="container-fluid">
        <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar"> <div class="sidebar-sticky">
        </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"> {% block body_block %}
        {% endblock %}
        <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2024 MyLibrary &middot; <a href="#">Privacy</a> &middot;
        <a href="#">Terms</a></p> </footer>
        </main>
        </div>
        </div>
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster --> 
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> 
        <script>
                window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
        </script>
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/
        feather.min.js"> </script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"> </script>
        </body>
        </html>
        

group_project-main/templates/mylibrary/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
<head lang="en">
<meta charset="UTF-8" />
<title>MyLibrary - {% block title_block %}MyLibrary{% endblock %}</title>
<body>
    <div>
    {% block body_block %}
    {% endblock %}
    </div>
    <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/mylibrary-jquery.js" %}" crossorigin="anonymous"></script>
    </body> 
</html>

group_project-main/templates/mylibrary/book.html
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<script src="{% static "js/book-jquery.js" %}" crossorigin="anonymous"></script>

{%extends 'mylibrary/base.html'%} 

{% block title_block %} 
{% if book %}
        {{ book.title }}
    {% else %}
        Book could not be found
    {% endif %}
{% endblock %}

{% block body_block %}
{% if category %}
<h1>{{ book.title }}</h1> 
<h1>{{ book.ISBN }}</h1> 
<h1>{{ book.author }}</h1> 
<h1>{{ book.uploadedBy }}</h1> 
{% endif %}
{% endblock %}

group_project-main/templates/mylibrary/index.html
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% extends 'mylibrary/base.html' %}

{% block title_block %}
MyLibrary
{% endblock %}

{% block body_block %}
Links:
<li><a href="{% url 'mylibrary:add_book' %}">Add Book</a></li>
<li><a href="{% url 'mylibrary:about' %}">About</a></li>
<li><a href="{% url 'mylibrary:myprofile' %}">MyProfile</a></li>
{% endblock %}

group_project-main/templates/mylibrary/mygoals.html
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% extends 'mylibrary/base.html' %}

{% load staticfiles %}

{% block title_block %}
These are your goals:
{% endblock %}
{% if goals %}
{% for goal in goals %}
<li><a href="{{ goal.slug }}">{{ goal.ISBN }}</a></li> {% endfor %}

{% block body_block %}
Links:
<li><a href="{% url 'mylibrary:add_book' %}">Add Book</a></li>
{% endblock %}

group_project-main/templates/mylibrary/myprofile.html
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% extends 'mylibrary/base.html' %}

{% load staticfiles %}

{% block title_block %}
Hello 
{% endblock %}

{% block body_block %}
<div>
Hello {{ request.user.username }}
You have been a member since {{ request.user.date_joined }}
Your current goals are:

</div>
Links:
<button class="btn btn-primary" id="about-btn"> Click me - I'm using JQuery!
</button>
<li><a href="{% url 'mylibrary:mygoals' %}">MyGoals</a></li>
{% endblock %}