group_project-main/group_work/urls.py
from django.urls import path, include
from mylibrary import views
from django.contrib import admin

urlpatterns = [
    path('', views.index, name='index'),
    path('mylibrary/', include('mylibrary.urls')),
    path("admin/", admin.site.urls),
]

group_project-main/mylibrary/urls.py
from django.urls import path
from mylibrary import views
from django.contrib import admin

app_name = 'mylibrary'


urlpatterns = [
    path('', views.index, name='index'),
    path('add_book/', views.add_book, name='add_book'),
    path('books/<slug:book_name_slug>/', views.show_book, name='show_book'),
    path('about/', views.about, name='about'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('mygoals/', views.mygoals, name='mygoals'),
    path('set_goal/', views.mygoals, name='set_goal'),

]

group_work/urls.py
from django.urls import path, include
from mylibrary import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('mylibrary/', include('mylibrary.urls')),
    path('category/<slug:category_name_slug>/', views.show_category, name = "show_category"),
    path('mylibrary/book/<slug:book_name_slug>/', views.show_book, name='show_book'),
    path('set_goal/', views.set_goal, name='set_goal'),
    path('myreviews/', views.myreviews, name='myreviews'),
    path('register/', views.register, name='register'),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mylibrary/urls.py
from django.urls import path
from mylibrary import views
from django.contrib import admin
from django.views import View
from mylibrary.views import user_read_book

app_name = 'mylibrary'


urlpatterns = [
    path('', views.index, name='index'),
    path('add_book/', views.add_book, name='add_book'),
    path('book/<slug:book_name_slug>/', views.show_book, name='show_book'),
    path('book/<slug:slug>/write_review/', views.write_review, name='write_review'),
    path('about/', views.about, name='about'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('mygoals/', views.mygoals, name='mygoals'),
    path('myreviews/', views.myreviews, name='myreviews'),
    path('search_results/', views.search_results, name='search_results'),
    path('set_goal/', views.set_goal, name='set_goal'),
    path('search/', views.search, name='search'),
    path('explorecategory/', views.explorecategory, name='explorecategory'),
    path('category/<slug:category_name_slug>', views.show_category, name='show_category'),
    path('logout/', views.user_logout, name='logout'),
    path('currentbooks/', views.curr_books, name='currentbooks'),
    path('user_read_book/', views.user_read_book.as_view(), name='user_read_book')
]

group_project-main/mylibrary/models.py
from django.db import models

# Create your models here.
from django.contrib import admin
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    categoryID=models.CharField(max_length=20, unique=True)
    numOfBooks=models.IntegerField(default=0)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileLink = models.URLField(blank=True)
    profilePic=models.ImageField()


class Book(models.Model):
    ISBN=models.IntegerField(unique=True)
    author=models.CharField(max_length=50)
    uploadedBy=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    coverPhoto=models.ImageField()
    categories = models.ManyToManyField(Category)
    title=models.CharField(max_length=500)
    slug=models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super(Book,self).save(*args, **kwargs)

class Goal(models.Model):
    goalAuthor=models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    dateSet=models.DateTimeField()
    achieved=models.BooleanField()
    goalID=models.CharField(max_length=50,unique=True)
    numPages=models.IntegerField(null=True)
    dateDay=models.IntegerField(null=True)
    dateMonth=models.IntegerField(null=True)
    dateYear=models.IntegerField(null=True)
    slug=models.SlugField(unique=True)


class Admin(models.Model):
    adminID=models.CharField(max_length=50, unique=True) 

class Review(models.Model):
    reviewID=models.CharField(max_length=50, unique=True)
    dateWritten=models.DateField()
    edited=models.BooleanField(default=False)
    reviewAuthorFK=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    reviewBookFK=models.ForeignKey(Book, on_delete=models.CASCADE, null=True)

group_project-main/mylibrary/forms.py
from django import forms
from mylibrary.models import Book, Category, Review, User, Goal, Admin
from django.contrib.auth.models import User 



class BookForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Enter the title of the book")
    author = forms.CharField(max_length=50, help_text="Enter the author of the book")
    ISBN = forms.IntegerField(help_text="Enter the ISBN of the book")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    book_dict = {"title": title, "author": author,"ISBN":ISBN, "uploadedBy":None}
    
    class Meta:
        model = Book
        fields=('title', 'author','ISBN','uploadedBy')

    def set_uploaded_by(self, user):
        self.book_dict["uploadedBy"]=user

    def get_book_dict(self):
        return self.book_dict

class GoalForm(forms.ModelForm):
    ISBN = forms.IntegerField(help_text="Enter the ISBN of the book this goal refers to")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    numPages=forms.IntegerField(help_text="How many pages do you want to read?")
    dateDay=forms.IntegerField(help_text="When do you want to achieve this by? Day: ")
    dateMonth=forms.IntegerField(help_text="Month: ")
    dateYear=forms.IntegerField(help_text="Year: ")

    
    class Meta:
        model = Goal
        fields=('goalAuthor', 'dateSet','goalID','achieved', 'slug', 'dateDay', 'dateMonth', 'dateYear')

group_project-main/mylibrary/views.py
from django.shortcuts import render
from mylibrary.forms import BookForm
from django.shortcuts import redirect
import django
from django.urls import reverse
import datetime
# Create your views here.

from django.http import HttpResponse 
from mylibrary.models import Book, Category, Review, User, Goal

def index(request):
    return render(request, 'mylibrary/index.html', context={})

def myprofile(request):
    user = User.objects.get(username=request.user.username)
    context_dict={"user":user}
    return render(request, 'mylibrary/myprofile.html', context_dict)


def set_goal(request):
    form = GoalForm()

    if request.method == 'POST':
        goal =  BookForm(request.POST)
        if form.is_valid():
            goal=form.save(commit=False)
            goal.goalAuthor=request.user
            goal.dateSet=datetime.datetime.now()
            goal.save()
            return redirect(reverse('mylibrary:mygoals'))
        else:
            print(form.errors)
    
    return render(request, 'mylibrary/mygoals.html', {'form': form})

def mygoals(request):
    context_dict={}
    goals = Goal.objects.filter(goalAuthor=request.user)
    context_dict["goals"] = goals
    return render(request, "mygoals.html", context=context_dict)

def show_book(request, book_name_slug):
    context_dict={}
    try:
        book=Book.objects.get(slug=book_name_slug)
        context_dict["book"]=book
    except Book.DoesNotExist:
        context_dict['category']=None
        context_dict['pages']=None
    return render(request, "mylibrary/book.html", context=context_dict)

def add_book(request):
    form = BookForm()

    if request.method == 'POST':
        form =  BookForm(request.POST)
        if form.is_valid():
            book=form.save(commit=False)
            book.uploadedBy=request.user
            book.save()
            show_book(request, book.slug)
            return redirect(reverse('mylibrary:show_book', kwargs={'book_name_slug': book.slug}))
        else:
            print(form.errors)
    
    return render(request, 'mylibrary/add_book.html', {'form': form})

def about(request):
    return render(request, 'mylibrary/about.html', context={})

mylibrary/views.py
from django.shortcuts import render
from mylibrary.forms import BookForm, UserProfileForm, UserForm, ReviewForm, GoalForm, CategoryForm
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import django
from django.urls import reverse
import datetime
from django.views import View
from django.contrib.auth.decorators import login_required
# Create your views here.

from django.http import HttpResponse 
from mylibrary.models import Book, Category, Review, User, Goal, UserProfile, BooksUserReading

def index(request):
    context_dict = {}
    book_list = Book.objects.order_by('-title').all()
    context_dict['book0'] = book_list[0]
    context_dict['book1'] = book_list[1]
    context_dict['book2'] = book_list[2]
    return render(request, 'mylibrary/index.html', context=context_dict)

def search(request):
    #results = Book.objects.filter(name__icontains=query)
    books = Book.objects.filter(title__icontains=request.GET.get('search'))
    context_dict = {}
    context_dict['books'] = books

    return render(request, 'mylibrary/search_results.html', context_dict)

def search_results(request):
    #results = Book.objects.filter(name__icontains=query)
    print(results)
    results = {}
    return render(request, 'mylibrary/search_results.html', {'results': results})    

def myprofile(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user.username)
        context_dict = {}
        context_dict['user'] = user
        context_dict={"user":user}
        return render(request, 'mylibrary/myprofile.html', context_dict)
    else:
        return redirect('/mylibrary/login/')

def write_review(request, slug):
 
    form = ReviewForm()
    book = Book.objects.filter(slug = slug).first()
 
    if request.method == 'POST':
        form =  ReviewForm(request.POST)
        if form.is_valid():
            review=form.save(commit=False)
            review.reviewID = book.slug + str(request.user) + str(review.message)
            review.reviewAuthorFK=request.user
            review.reviewBookFK = Book.objects.filter(slug = slug).first()
            review.save()
            return redirect('myreviews')
        else:
            form = ReviewForm()
            print(form.errors)
   
    return render(request, 'mylibrary/write_review.html', {'form': form, 'book':book})


def explorecategory(request):

    #book_list = Book.objects.order_by('-likes')[:5]
    book_list = Book.objects.all()
    category_list = Category.objects.all()
    context_dict = {}
    context_dict['categories'] = category_list
    #context_dict['books'] = book_list
    #context_dict['book'] = book_list
    print(context_dict)
    #context_dict['book'] = book_list

    #images = Book.
    return render(request, 'mylibrary/explorecategory.html', context = context_dict)
    

def user_login(request):
    if request.method ==  'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('mylibrary:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"invalid login details:{username}, {password}")
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request,'mylibrary/login.html', {})


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save(commit = False)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profilePic' in request.FILES:
                profile.profilePic = request.FILES['profilePic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, "mylibrary/register.html", context = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

@login_required
def set_goal(request):
    form = GoalForm()

    if request.method == 'POST':
        goal =  BookForm(request.POST)
        if form.is_valid():
            form=form.save(commit=False)
            form.goalAuthor=request.user
            form.dateSet=datetime.datetime.now()
            form.save()

        else:
            print(form.errors)
    
    return render(request, "mylibrary/set_goal.html", {'form': form})

@login_required
def mygoals(request):
    context_dict={}
    goals = Goal.objects.filter(goalAuthor=request.user)
    context_dict["goals"] = goals
    return render(request, "mylibrary/mygoals.html", context=context_dict)

def myreviews(request):
    if request.user.is_authenticated:
        context_dict={}
        review = Review.objects.filter(reviewAuthorFK=request.user)
        context_dict["reviews"] = review
        return render(request, "mylibrary/myreviews.html", context=context_dict)
    else:
        return redirect('/mylibrary/login/')

def show_book(request,book_name_slug):
    if request.user.is_authenticated:
        try:
            book=Book.objects.get(slug=book_name_slug)
            review=Review.objects.filter(reviewBookFK=book) #maybe add in an order by feature
            categories = book.categories.all()
            context_dict={}
            context_dict["book"]=book
            context_dict["reviews"]=review
            context_dict["user"] = UserProfile.objects.get(user=request.user)
            context_dict["categories"] = categories
            try:
                userReads = BooksUserReading.objects.get(userFK=UserProfile.objects.get(user=request.user), bookFK=book)
                context_dict['read'] = False
                context_dict['relation'] = userReads
            except BooksUserReading.DoesNotExist:
                context_dict['read'] = True
                print(context_dict['read'])
        except Book.DoesNotExist:
            context_dict['category']=None
            context_dict['pages']=None
            context_dict['readingList']=None
        return render(request, "mylibrary/book.html", context=context_dict)
    else:
        return redirect('/mylibrary/register/')


def curr_books(request):
    context_dict={}
    context_dict['books'] = BooksUserReading.objects.filter(userFK=UserProfile.objects.get(user=request.user))
    for book in context_dict['books']:
        print(book.bookFK.title)
    return render(request, "mylibrary/currentbooks.html", context=context_dict)

def show_category(request, category_name_slug):

    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)

        books = Book.objects.filter(categories = category)
        print(books)

        context_dict['books'] = books
        context_dict['category'] = category

    except Category.DoesNotExist:

        context_dict['category'] = None
        context_dict['books'] = None

    return render(request, 'mylibrary/category.html', context=context_dict)

def add_book(request):
    if request.user.is_authenticated:
        form = BookForm()

        if request.method == 'POST':
            form =  BookForm(request.POST, request.FILES)
            if form.is_valid():
                book=form.save(commit=False)
                book.uploadedBy=request.user
                categories = form.cleaned_data['categories']
                if 'photoCover' in request.FILES:
                    book.photoCover = request.FILES['photoCover']
                book.save()
                book.categories.set(categories)
                show_book(request, book.slug)
                return redirect(reverse('mylibrary:show_book', kwargs={'book_name_slug': book.slug}))
            else:
                print(form.errors)
        
        return render(request, 'mylibrary/add_book.html', {'form': form})
    else:
        return redirect('/mylibrary/login/')

def about(request):
    return render(request, 'mylibrary/about.html', context={})

class user_read_book(View):
    def get(self,request):
        bookISBN = request.GET['bookISBN'] 
        book = Book.objects.get(ISBN=int(bookISBN))
        userID = request.GET['user']
        user = User.objects.get(username = userID)
        userProfile = UserProfile.objects.get(user = user)
        object = BooksUserReading.objects.get_or_create(userFK=userProfile,bookFK=book)[0]
        object.userFK=userProfile
        object.bookFK=book
        object.pagesRead = 0
        object.startedReading = datetime.datetime.now
        #object.save()
        return HttpResponse("Hello")

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('mylibrary:index'))

templates/mylibrary/about.html
<!DOCTYPE html>

{% extends 'mylibrary/base.html' %}
{% load staticfiles %}

{% block title_block %}
About MyLibrary
{% endblock %}
{% block body_block %}
<div><strong>This website has been put together by Juliet Wallace, Edwin Barnes and Dylan Stair.</strong><br /> </div>
<div><strong>The scope of this web app is to allow users to have their own library, with functionalities such as writing and reading reviews, adding and exploring books.</strong><br /> </div>
{% endblock %}

templates/mylibrary/add_book.html
<!DOCTYPE html>

{% extends 'mylibrary/base.html' %} 

{% block title_block %}
Add a Book
{% endblock %}

{% block body_block %}
<form id="book_form" method="post" action="/mylibrary/add_book/" enctype="multipart/form-data"> 
  {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
<div class="container mt-5">
  <div class="row">
{% for field in form.visible_fields %}
      <div class="col-sm-4">
        {{ field }}
        {{ field.errors }}
        {{ field.help_text }}
      </div>
{% endfor %}
</div>
</div>

<div class="container mt-5">
    <div class="col">
      <div class="col-sm-4">
        <input type="submit" name="submit" value="Upload Book" />
         </form>
         <div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/mylibrary/base-new.html
<!DOCTYPE html>
{%load staticfiles% }
<html lang="en"> <head>
<meta
<link <title>
MyLibrary - {% block title_block %}MyLibrary{% endblock %} </title>
  <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
<link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
</head> <body> <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0"> <a class="navbar-brand p-2" href="{% url 'mylibrary:index' %}">MyLibrary</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse"> <ul class="navbar-nav mr-auto">
    <li class="nav-item">
    <a class="nav-link" href="{% url 'mylibrary:index' %}">Home</a></li> <li class="nav-item ">
    Bootstrapping Rango 208
    <li
    class="nav-item ">
    href="{% url 'mylibrary:add_book' %}">Add a Book</a></li> class="nav-item">
    <a class="nav-link"
    class="nav-item">
    </header>
    <div class="container-fluid">
        <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar"> <div class="sidebar-sticky">
        </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"> {% block body_block %}
        {% endblock %}
        <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2024 MyLibrary &middot; <a href="#">Privacy</a> &middot;
        <a href="#">Terms</a></p> </footer>
        </main>
        </div>
        </div>
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster --> 
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> 
        <script>
                window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
        </script>
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/
        feather.min.js"> </script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"> </script>
        </body>
        </html>
        

templates/mylibrary/book.html
<!DOCTYPE html>
{% extends 'mylibrary/base.html' %}
{{ MEDIA_URL }}
{% load staticfiles %}
{% block body_block %}
<html>

    <head>
        <title>Book</title>
    </head>

    <body>
        <div>
            <div class="container mt-6">
                <div class="col">
                  <div class="col-sm-4">
                    {% if book %}
                    <h1>{{ book }} by {{ book.author }}</h1></br>
                    <h5>Uploaded by {{ book.uploadedBy }}</h5>
                    {% endif %}
                  </div>
                </div>
              </div>
    </div>

    <div>
            <div class="container mt-5">
                <div class="row">
                  <div class="col-sm-4">
                    <h4>Categories:</h4>
                    {% for category in categories %}
                    <h6>{{ category }}</h6>
                    {% endfor %}
                  </div>
                </div>
                  <div class="col-sm-5">
                    <img src="{{ MEDIA_URL }}{{ book.coverPhoto }}" style="width:300px;height:300px;">
                </div>
              </div>

            {% for review in reviews %}
            <div class="container mt-5">
                <div class="col">
                  <div class="col-sm-4">
                    <h3>{{review.reviewAuthorFK}} {{review.dateWritten}}</h3>
                    {% if review.reviewAuthorFK.userprofile.profilePic %}
                    <img src="{{MEDIA_URL}}{{ review.reviewAuthorFK.userprofile.profilePic }}" style="width:50px;height:50px;">
                    {% else %}
                    <img src="{{MEDIA_URL}}/profile_images/Guest.png" style="width:50px;height:50px;">
                    {% endif %}
                    <p>{{ review.message }}</p>
                  </div>
                </div>
              </div>
            {% endfor %}
            <li><a href="/mylibrary/book/{{ book.slug }}/write_review">Write review</a></li>
            <div>
            {% if read %}
            <button id="readButton" data-totalPages="{{ book.totalPages }}" data-pagesRead="{{ book.pagesRead }}">Stop Reading</button>
            {% else %}
            <h5 id="readHeader">Click this button to upload this book to your library!</h5>
            <button id="readButton" data-book="{{ book.ISBN }}" data-userID="{{ user.user }}">Start Reading</button>
            {% endif %}
            </div>
    </div>
    </body>

</html>
{% endblock %}

templates/mylibrary/category.html
<!DOCTYPE html>
{% extends 'mylibrary/base.html' %}
{% block body_block %}
<html>

    <head>
        <title>{{ category.categoryID }}</title>
    </head>

    <body>
    <div>
        <div class="container mt-5">
        <div class="col">
        <div class="col-sm-4">
        {% if category %}
            <h1>{{ category.categoryID }}</h1>
            {% if books %}
            </div>
            </div>
            </div>
            <ul>
                {% for book in books %}
                <div class="container mt-5">
                <div class="col">
                  <div class="col-sm-4">
                    <li><a href="/mylibrary/book/{{ book.slug }}/">{{ book.title }}</a></li>
                  </div>
                </div>
              </div>
                {% endfor %}
            </ul>
            {% else %}
            <strong>No books currently in category.</strong>
            {% endif %}
        {% endif %}
    </div>
    </body>

</html>
{% endblock %}

templates/mylibrary/index.html
<!DOCTYPE html>

{% extends 'mylibrary/base.html' %}
{% load staticfiles %}
{{ MEDIA_URL }}
<link rel="stylesheet" href="{% static 'idk.css' %}">

{% block title_block %}
MyLibrary
{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}
<h1> Welcome back {{ user.username }}</h1>
{% else %}
    You are not logged in
{% endif %}

<!-- Slideshow container -->
<div class="slideshow-container">

    <!-- Full-width images with number and caption text -->
    <div class="mySlides fade">
      <div class="numbertext">1 / 3</div>
      {% if book0 %}
      <img src="{{ MEDIA_URL }}{{ book0.coverPhoto }}" style="width:500px;height:300px;">
      {% endif %}
    </div>
  
    <div class="mySlides fade">
      <div class="numbertext">2 / 3</div>
      {% if book1 %}
      <img src="{{ MEDIA_URL }}{{ book1.coverPhoto }}" style="width:500px;height:300px;">
      {% endif %}
    </div>
  
    <div class="mySlides fade">
      <div class="numbertext">3 / 3</div>
      {% if book2 %}
      <img src="{{ MEDIA_URL }}{{ book2.coverPhoto }}" style="width:500px;height:300px;">
      {% endif %}
    </div>
  
    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <br>
  
  <!-- The dots/circles -->
  <div style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
  </div>

{% endblock %}

templates/mylibrary/login.html
{% extends 'mylibrary/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to MyLibrary</h1>
<form id="login_form" method="post" action="{% url 'mylibrary:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/mylibrary/mygoals.html
<!DOCTYPE html>

{% extends 'mylibrary/base.html' %}

{% load staticfiles %}

{% block title_block %}
These are your goals:
{% endblock %}

{% if goals %}
{% for goal in goals %}
<li><a href="{{ goal.slug }}">{{ goal.ISBN }}</a></li> 
{% endfor %}
{% endif %}


{% block body_block %}
Links:
{% if goals %}
{% for goal in goals %}
<li><a href="{{ goal.slug }}">{{ goal.ISBN }}</a></li> 
{% endfor %}
{% endif %}
<li><a href="{% url 'mylibrary:set_goal' %}">Set Goal</a></li>
{% endblock %}

templates/mylibrary/myprofile.html
<!DOCTYPE html>

{% extends 'mylibrary/base.html' %}

{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block body_block %}
<div>
Hello {{ request.user.username }}
{% if user.userprofile.profilePic %}
    <img src="{{MEDIA_URL}}{{ user.userprofile.profilePic }}" style="width:300px;height:300px">
{% else %}
    <img src="{% static 'img/Guest.png' %}" style="width:300px;height:300px;">
{% endif %}

You have been a member since {{ request.user.date_joined }}
</div>
Links:
<li><a href="{% url 'mylibrary:myreviews' %}">MyReviews</a></li>
{% endblock %}

templates/mylibrary/register.html
<!DOCTYPE html>

{% extends 'mylibrary/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for MyLibrary</h1>
{% if registered %}
<div class="alert alert-success"> <strong> Thank you for registering! </strong></div>
<a href="{% url 'mylibrary:index' %}">Return to the homepage</a><br/>
{% else %}
<form id="user_form" method="post" action="{% url 'mylibrary:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container mt-5">
        <div class="col">
          <div class="col-sm-4">
            {{ user_form.as_p }}
          </div>
          <div class="col-sm-4">
            {{ profile_form.as_p}}
          </div>
        </div>
      </div>
    <input type="submit" name = "submit" value="Register"/>
</form>
{% endif %}
{% endblock %}